language: python
sudo: false
addons:
  apt:
    packages:
    - libev-dev
    - libsnappy-dev
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27 BROKERS=localhost:9092,localhost:9093,localhost:9094 ZOOKEEPER=localhost:2181 KAFKA_BIN=/home/travis/kafka-bin
    - python: 3.4
      env: TOXENV=py34 BROKERS=localhost:9092,localhost:9093,localhost:9094 ZOOKEEPER=localhost:2181 KAFKA_BIN=/home/travis/kafka-bin
    - python: 3.5
      env: TOXENV=py35 BROKERS=localhost:9092,localhost:9093,localhost:9094 ZOOKEEPER=localhost:2181 KAFKA_BIN=/home/travis/kafka-bin
    - python: pypy
      env: TOXENV=pypy BROKERS=localhost:9092,localhost:9093,localhost:9094 ZOOKEEPER=localhost:2181 KAFKA_BIN=/home/travis/kafka-bin

notifications:
  email:
    - keith@parsely.com
    - emmett@parsely.com


install:
    - pip install codecov kazoo tox testinstances futures

before_script:
    - "python -m pykafka.test.kafka_instance 3 --download-dir /home/travis/kafka-bin &"
    - "sleep 10"

script:
    - tox

# Calculate coverage on success
after_success:
    - codecov

branches:
  only:
    - master
